using System.Windows;
using System.Windows.Controls;
using EE.Doklad.Models;
using EE.Doklad.Services;
using EE.Doklad.ViewModels;

namespace EE.Doklad.Views
{
    /// <summary>
    /// Прозорец „Методика (БГВ)" – регенерируеми загуби от разпределителна система.
    /// Отваря се от бутон в HotWaterSectionEditor.
    /// </summary>
    public partial class DhwLossMethodologyWindow : Window
    {
        public DhwLossCalculatorViewModel ViewModel { get; }

        /// <summary>
        /// Инициализира прозореца.
        /// </summary>
        /// <param name="workingDaysPerYear">Брой работни дни (от Section 16)</param>
        /// <param name="hotWaterTemp">Температура на БГВ [°C]</param>
        /// <param name="initialMode">Текущо избраният режим в Section 16</param>
        /// <param name="onConfirm">Callback (kWh/год, f_rbl%) – извиква се при потвърждаване</param>
        public DhwLossMethodologyWindow(
            double workingDaysPerYear,
            double hotWaterTemp,
            DhwLossMode initialMode,
            System.Action<double, double>? onConfirm = null)
        {
            var service = new DhwDistributionLossService();

            ViewModel = new DhwLossCalculatorViewModel(
                service,
                workingDaysPerYear,
                hotWaterTemp,
                onConfirm: (qRbl, fPct) =>
                {
                    onConfirm?.Invoke(qRbl, fPct);
                    DialogResult = true;
                    Close();
                });

            ViewModel.SelectedMode = initialMode;

            DataContext = ViewModel;
            // CS0103: InitializeComponent is generated by the XAML compiler into obj\...g.cs
#pragma warning disable CS0103
            InitializeComponent();
#pragma warning restore CS0103
        }

        private void CloseButton_Click(object sender, RoutedEventArgs e)
        {
            DialogResult = false;
            Close();
        }

        private void CalculateButton_Click(object sender, RoutedEventArgs e)
        {
            // Commit any pending edits in the DataGrids so bindings update the model.
            // CS0103 suppressions below: SegmentsDataGrid / StubZonesDataGrid are generated
            // by the XAML compiler into obj\...g.cs and are invisible to the IDE language
            // server. The build succeeds – these are IntelliSense-only false positives.
#pragma warning disable CS0103
            try
            {
                SegmentsDataGrid.CommitEdit(DataGridEditingUnit.Cell, true);
                SegmentsDataGrid.CommitEdit(DataGridEditingUnit.Row, true);

                StubZonesDataGrid.CommitEdit(DataGridEditingUnit.Cell, true);
                StubZonesDataGrid.CommitEdit(DataGridEditingUnit.Row, true);
            }
            catch
            {
                // ignore commit failures – we'll still attempt calculation
            }
#pragma warning restore CS0103

            // Invoke the ViewModel command after edits are committed
            if (ViewModel?.CalculateCommand?.CanExecute(null) == true)
                ViewModel.CalculateCommand.Execute(null);
        }
    }
}
