<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="PDFsharp-MigraDoc" Version="6.2.4" />
    <PackageReference Include="QuestPDF" Version="2025.12.2" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Data\climate_zones.json" />
    <EmbeddedResource Include="Data\materials.seed.json" />
    <EmbeddedResource Include="Data\lighting.seed.json" />
    <EmbeddedResource Include="Data\appliances.seed.json" />
    <EmbeddedResource Include="Data\DefaultParams_climateZones_hourly_flat_1to9.json" />
  </ItemGroup>



</Project>
